services:
  auth:
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
      - rabbitmq

  user:
    build:
      context: .
      dockerfile: Bank.Api/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
      - rabbitmq

  email:
    build:
      context: .
      dockerfile: Email.Api/Dockerfile
    ports:
      - "5003:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
      - rabbitmq

  pix:
    build:
      context: .
      dockerfile: Pix.Api/Dockerfile
    ports:
      - "5004:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
      - rabbitmq

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5005:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - user
      - auth
      - email
      - pix

  payments:
    build: ./Payments.Api
    ports:
      - "${PAYMENTS_PORT:-5007}:8080"
    networks:
      - appnet
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PaymentsBank;User Id=sa;Password=Senha123!;TrustServerCertificate=True

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senha123!
    ports:
      - "1433:1433"
    networks:
      - appnet
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta de comunicação
      - "15672:15672"  # Painel de gerenciamento web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - appnet
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  appnet:
    driver: bridge

volumes:
  sqlserver_data:
  rabbitmq_data:
