services:
  auth:
    build: ./Auth.Api
    ports: ["5001:8080"]
    networks: [appnet]

  user:
    build: ./Bank.Api
    ports: ["5002:8080"]
    networks: [appnet]
    depends_on:
      - sqlserver

  email:
    build: ./Email.Api
    ports: ["5003:8080"]
    networks: [appnet]
    depends_on:
      - sqlserver

  pix:
    build: ./Pix.Api
    ports: ["5004:8080"]
    networks: [appnet]
    depends_on:
      - sqlserver

  report:
    build: ./ReportApi
    ports: ["5006:8080"]
    networks: [appnet]

  apigateway:
    build: ./ApiGateway
    ports: ["5005:8080"]
    networks: [appnet]
    depends_on: 
      - user
      - auth
      - email
      - pix
      - report

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senha123!
    ports:
      - "1433:1433"
    networks:
      - appnet
    restart: always

networks:
  appnet:
    driver: bridge