services:
  auth:
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  user:
    build:
      context: .
      dockerfile: Bank.Api/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  email:
    build:
      context: .
      dockerfile: Email.Api/Dockerfile
    ports:
      - "5003:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  pix:
    build:
      context: .
      dockerfile: Pix.Api/Dockerfile
    ports:
      - "5004:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  report:
    build: ./ReportApi
    ports: [ "5006:8080" ]
    networks: [ appnet ]

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5005:8080"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - user
      - auth
      - email
      - pix
      - report

  payments:
    build: ./Payments.Api
    ports:
      - "${PAYMENTS_PORT:-5007}:8080"
    networks:
      - appnet
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PaymentsBank;User Id=sa;Password=Senha123!;TrustServerCertificate=True
  ai:
    build: ./Ai.Api
    ports:
      - "${AI_PORT:-5008}:8080"
    networks:
      - appnet
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Senha123!
    ports:
      - "1433:1433"
    networks:
      - appnet
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta de comunicação
      - "15672:15672"  # Painel de gerenciamento web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - appnet
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  appnet:
    driver: bridge

volumes:
  sqlserver_data:
  rabbitmq_data: