// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pix.Api.Data;

#nullable disable

namespace Pix.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:Pix.Api/Migrations/20250716134319_new_migrate.Designer.cs
    [Migration("20250716134319_new_migrate")]
    partial class new_migrate
========
    [Migration("20250717025708_Initial")]
    partial class Initial
>>>>>>>> 8dd7f9160fe4f4c2b27a6dd08224c7154dafeb6d:Pix.Api/Migrations/20250717025708_Initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pix.Api.Models.PixModel", b =>
                {
                    b.Property<Guid>("IdPix")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPix");

                    b.HasIndex("PixKey")
                        .IsUnique();

                    b.ToTable("Pix");
                });

            modelBuilder.Entity("Pix.Api.Models.TransactionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coming")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Going")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
